---
- hosts: fortigates
  connection: httpapi
  gather_facts: no
  collections:
  - fortinet.fortios
  
  vars:
    vdom: "{{ vdom }}"
  
  tasks:
    - name: Save config revision on FortiGate
      fortinet.fortios.fortios_monitor:
        vdom: "{{ vdom }}"
        selector: "save.system.config-revision"

        
    - name: Backup Syatem config on FortiGate
      fortinet.fortios.fortios_monitor:
        vdom: "{{ vdom }}"
        selector: "backup.system.config"

