---
- hosts: fortigates
  connection: httpapi
  gather_facts: no
  collections:
  - fortinet.fortios
  
  vars:
    vdom: "root"
    
  tasks:
    - name: Backup a virtual domain.
      fortinet.fortios.fortios_monitor:
       access_token: "{{ fortios_access_token }}"
       selector: 'backup.system.config'
       vdom: "{{ vdom }}"
       params:
           scope: 'global'
      register: backupinfo

    - name: Save the backup information.
      copy:
       content: '{{ backupinfo.meta.raw }}'
       dest: '/tmp/fw1.cfg'
      delegate_to: 192.168.204.7
      run_once: true
