---
- hosts: fortigates
  connection: httpapi
  collections:
  - fortinet.fortios
  
  tasks:
  - name: Save config revision on FortiGate
    fortinet.fortios.fortios_monitor:
      vdom: "root"
      selector: "save.system.config-revision"

        
  - name: Backup Syatem config on FortiGate
    fortinet.fortios.fortios_monitor:
      vdom: "root"
      selector: "backup.system.config"

