---
- hosts: fortigates
  connection: httpapi
  collections:
  - fortinet.fortios
  
  tasks:
  - name: Save config revision on FortiGate
    fortinet.fortios.fortios_monitor:
      vdom: "root"
      selector: "save.system.config-revision"
      access_token: "{{ fortigate_api_token }}"
      params:
        name: "pre-upgrade-snapshot"
        comment: "Auto backup before firmware upgrade"
