---
- hosts: fortigate01
  connection: httpapi
  collections:
  - fortinet.fortios
  
  tasks:
  - name: change_hostname
    fortios_system_global:
      vdom:  "{{ vdom }}"
      system_global:
          admintimeout: "60"
          hostname: "pptech_FW01"
