- hosts: fortigate01
  connection: httpapi
  collections:
  - fortinet.fortios
  vars:
   vdom: "root"
   ansible_httpapi_use_ssl: true
   ansible_httpapi_validate_certs: false
   ansible_httpapi_port: 80
  tasks:
  - name: Change hostname
    fortios_system_global:
      vdom:  "{{ vdom }}"
        system_global:
          hostname: 'YOUR_OWN_VALUE'
