---
- hosts: fortigates
  gather_facts: false
  connection: httpapi
  vars:
    vdom: root
  tasks:
    - name: Change hostname
      fortinet.fortios.fortios_system_global:
        vdom: "{{ vdom }}"
        system_global:
          hostname: "Fortigate01"
        state: present
        access_token: "{{ fortigate_api_token }}"
        use_ssl: true
        validate_certs: false
