---
- name: Change FortiGate Hostname
  hosts: fortigates
  connection: httpapi
  gather_facts: no
  collections:
    - fortinet.fortios

  vars:
    vdom: "root"

  tasks:
    - name: Set FortiGate hostname
      fortios_system_global:
        access_token: "{{ fortigate_api_token }}"
        vdom: "{{ vdom }}"
        system_global:
          hostname: 'Fortigate01'
