- hosts: fortigate01
  connection: httpapi
  gather_facts: no
  collections:
    - fortinet.fortios

  vars:
    vdom: "root"

  tasks:
    - name: Get update firmware version
      fortinet.fortios.fortios_monitor:
        vdom: "{{ vdom }}"
        selector: "update.system.fortiguard"
      register: version_info
    
    - name: Show current firmware
      debug:
        var: version_info.meta.version
