- name: Apply Fortigate Update with Local Firmware File
  hosts: fortigate01
  connection: httpapi
  collections:
  - fortinet.fortios
  tasks:
  - name: Firmware Upgrade
    fortinet.fortios.fortios_monitor:
      vdom: "{{ vdom }}"
      enable_log: true
      selector: "upgrade.system.firmware"
      
      params:
        source: "ftp"
        hostname: "192.168.179.108"  
        filename: "FGT_VM64-v7.6.3.F-build3510-FORTINET.out"
        username: "anonymous"  
        password: ""
        file_content: "{{ lookup('file', 'FGT_VM64-v7.6.3.F-build3510-FORTINET.out') | b64encode }}"
    register: upgrade_result
