- name: Apply Fortigate Update with Local Firmware File
  hosts: fortigate01
  connection: httpapi
  collections:
  - fortinet.fortios
  vars:
    local_firmware_file_path: "firmware/FOS_VM64_KVM-v7.2.11.M-build1740-FORTINET.out"
    remote_firmware_filename: "FOS_VM64_KVM-v7.2.11.M-build1740-FORTINET.out"
    ansible_httpapi_timeout: 300

  tasks:
  - name: Firmware Upgrade
    fortinet.fortios.fortios_monitor:
      vdom: "{{ vdom }}"
      enable_log: true
      selector: "upgrade.system.firmware"
      params:
        source: "upload"
        filename: "{{ remote_firmware_filename }}"
        file_content: "{{ lookup('file', './firmware/FOS_VM64_KVM-v7.2.11.M-build1740-FORTINET.out') | b64encode }}"
    register: upgrade_result


  - name: Show result
    debug:
      var: upgrade_result


