- name: Apply FortiGate Update via FTP
  hosts: fortigate01
  connection: httpapi
  collections:
    - fortinet.fortios

  vars:
    vdom: "root"

  tasks:
    - name: Trigger firmware upgrade from FTP
      fortinet.fortios.fortios_monitor:
        vdom: "{{ vdom }}"
        enable_log: true
        selector: "upgrade.system.firmware"
        params:
          source: "ftp"
          url: "ftp://anonymous:@192.168.179.108/FGT_VM64-v7.6.3.F-build3510-FORTINET.out"
          filename: "FGT_VM64-v7.6.3.F-build3510-FORTINET.out"
      register: upgrade_result

    - name: Show result
      debug:
        var: upgrade_result
