- name: Upgrade FortiGate firmware from FortiGuard
  hosts: fortigate01
  connection: httpapi
  gather_facts: no
  collections:
    - fortinet.fortios

  vars:
    vdom: "root"

  tasks:
    - name: firmware upgrade
      fortinet.fortios.fortios_system_fortiguard:
        vdom: "{{ vdom }}"
        system_fortiguard:
          auto_firmware_upgrade: "enable"
          auto_firmware_upgrade_start_hour: "0"
      register: result    

    - name: Show result
      debug:
        var: result
