- name: Upgrade FortiGate firmware from FortiGuard
  hosts: fortigate01
  connection: httpapi
  gather_facts: no
  collections:
    - fortinet.fortios

  vars:
    vdom: "root"

  tasks:
    - name: Trigger firmware upgrade from FortiGuard
      fortinet.fortios.fortios_monitor:
        vdom: "{{ vdom }}"
        selector: "upgrade.system.firmware"
        params:
          source: "fortiguard"
      register: result

    - name: Show result
      debug:
        var: result
