- name: Upgrade FortiGate firmware from FortiGuard
  hosts: fortigates
  connection: httpapi
  gather_facts: no
  collections:
    - fortinet.fortios

  vars:
    vdom: "root"

  tasks:
    - name: Firmware Upgrade from FortiGuard
      fortinet.fortios.fortios_monitor:
        vdom: "{{ vdom }}"
        enable_log: true
        selector: "upgrade.system.firmware"
        params:
          source: "fortiguard"
      register: upgrade_result  

    - name: Show result
      debug:
        var: result
