- name: Apply FortiGate patch
  hosts: fortinet
  gather_facts: no
  connection: httpapi
  vars_files:
    - group_vars/fortinet.yml
  tasks:
    - name: Upgrade firmware from FortiGuard
      fortinet.fortios.fortios_system_firmware_upgrade:
        vdom: "{{ vdom }}"
        system_firmware:
          source: "fortiguard"
      register: upgrade_result

    - name: Save upgrade result
      copy:
        content: "{{ upgrade_result | to_nice_json }}"
        dest: "/tmp/firmware_upgrade_result.json"
