- name: Check and compare FortiGate patch availability
  hosts: fortinet
  gather_facts: no
  connection: httpapi
  vars_files:
    - group_vars/fortinet.yml
  tasks:
    - name: Get current firmware version
      fortinet.fortios.fortios_system_status:
        vdom: "{{ vdom }}"
      register: current_status

    - name: Check available firmware from FortiGuard
      fortinet.fortios.fortios_system_firmware_check:
        vdom: "{{ vdom }}"
      register: firmware_check_result

    - name: Set facts for comparison
      set_fact:
        current_version: "{{ current_status.meta.version }}"
        latest_version: "{{ firmware_check_result.meta.version }}"

    - name: Print firmware versions
      debug:
        msg: "Current: {{ current_version }}, Latest: {{ latest_version }}"

    - name: Save firmware check result to file
      copy:
        content: "{{ firmware_check_result | to_nice_json }}"
        dest: "/tmp/firmware_check_result.json"

    - name: Save current firmware status to file
      copy:
        content: "{{ current_status | to_nice_json }}"
        dest: "/tmp/current_firmware_status.json"

    - name: Fail if no new patch is available
      fail:
        msg: "No new firmware patch available. Current version is up-to-date."
      when: current_version == latest_version
