- name: Notify IT team of patch result
  hosts: localhost
  gather_facts: no
  vars_files:
    - group_vars/fortinet.yml
  tasks:
    - name: Read upgrade result
      slurp:
        src: "/tmp/firmware_upgrade_result.json"
      register: slurped_result

    - name: Decode and parse JSON
      set_fact:
        upgrade_result: "{{ slurped_result['content'] | b64decode | from_json }}"

    - name: Send result email
      community.general.mail:
        host: smtp.example.com
        port: 587
        username: patchbot@example.com
        password: "{{ email_password }}"
        to: it_team@example.com
        subject: "Patch Result for FortiGate {{ inventory_hostname }}"
        body: |
          Patch operation completed.
          Status: {{ upgrade_result.meta.status }}
          Version: {{ upgrade_result.meta.version }}
